name: weather_app_youtube
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.0.1
  weather: ^3.1.1
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  permission_handler: ^11.1.0
  timer_builder: ^2.0.0
  equatable: ^2.0.5
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
