name: weather_app_youtube
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:

  flutter:
    sdk: flutter

  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.5
  geolocator: ^10.1.0
  intl: ^0.19.0
  permission_handler: ^11.0.1
  timer_builder: ^2.0.0
  universal_io: ^2.2.0
  weather: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
